/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/credentials/{credential_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Credential */
        put: operations["put_credential_api_v1_settings_credentials__credential_id__put"];
        post?: never;
        /** Delete Credential */
        delete: operations["delete_credential_api_v1_settings_credentials__credential_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/credentials/{credential_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Credential */
        post: operations["test_credential_api_v1_settings_credentials__credential_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tts/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tts Voices */
        get: operations["list_tts_voices_api_v1_tts_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs V1 */
        get: operations["list_jobs_v1_api_v1_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_v1_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/retranslate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retranslate Job */
        post: operations["retranslate_job_api_v1_jobs__job_id__retranslate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Job */
        post: operations["render_job_api_v1_jobs__job_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Job */
        post: operations["approve_job_api_v1_jobs__job_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/unapprove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unapprove Job */
        post: operations["unapprove_job_api_v1_jobs__job_id__unapprove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Glossary */
        get: operations["get_glossary_api_v1_jobs__job_id__glossary_get"];
        /** Put Glossary */
        put: operations["put_glossary_api_v1_jobs__job_id__glossary_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/subtitles/{lang}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subtitles */
        get: operations["get_subtitles_api_v1_jobs__job_id__subtitles__lang__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/subtitle-overrides/{lang}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Subtitle Overrides */
        put: operations["put_subtitle_overrides_api_v1_jobs__job_id__subtitle_overrides__lang__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/tts/vi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tts Workspace */
        get: operations["get_tts_workspace_api_v1_jobs__job_id__tts_vi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/tts/vi/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Tts Settings */
        put: operations["put_tts_settings_api_v1_jobs__job_id__tts_vi_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/tts/vi/spoken-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Tts Spoken Overrides */
        put: operations["put_tts_spoken_overrides_api_v1_jobs__job_id__tts_vi_spoken_overrides_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/tts/vi/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Tts */
        post: operations["preview_tts_api_v1_jobs__job_id__tts_vi_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/tts/vi/calibrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calibrate Tts */
        post: operations["calibrate_tts_api_v1_jobs__job_id__tts_vi_calibrate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/tts/vi/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Tts */
        post: operations["render_tts_api_v1_jobs__job_id__tts_vi_render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/tts/vi/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Tts */
        post: operations["approve_tts_api_v1_jobs__job_id__tts_vi_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/tts/vi/unapprove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unapprove Tts */
        post: operations["unapprove_tts_api_v1_jobs__job_id__tts_vi_unapprove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/tts/vi/previews/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Tts Preview */
        get: operations["download_tts_preview_api_v1_jobs__job_id__tts_vi_previews__segment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** File Roots Endpoint */
        get: operations["file_roots_endpoint_api_v1_files_roots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["list_files_api_v1_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Media */
        get: operations["job_media_api_v1_jobs__job_id__media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_api_v1_jobs__job_id__artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddressTerm
         * @description Vietnamese address terms are a **pairwise** relation and do not fit the
         *     ``{zh, pinyin, vi, en}`` shape of :class:`GlossaryTerm`, hence a separate
         *     section.
         */
        AddressTerm: {
            /** Speaker */
            speaker: string;
            /** Addressee */
            addressee: string;
            /** Vi Self */
            vi_self: string;
            /** Vi Other */
            vi_other: string;
            /**
             * Basis
             * @default
             */
            basis: string;
        };
        /** ApiMessage */
        ApiMessage: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Artifact Id */
            artifact_id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "subtitle" | "audio" | "report" | "other";
            /** Language */
            language?: string | null;
            /** Format */
            format?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Created At */
            created_at?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "current" | "stale" | "missing";
            /** Download Url */
            download_url?: string | null;
        };
        /** CreateJobRequest */
        CreateJobRequest: {
            source: components["schemas"]["SourceRequest"];
            /** Targets */
            targets?: ("vi" | "en")[];
            /** Formats */
            formats?: ("srt" | "ass")[];
            /**
             * Bilingual
             * @default false
             */
            bilingual: boolean;
        };
        /** CreateJobResponse */
        CreateJobResponse: {
            /** Job Id */
            job_id: string;
            /** Run Id */
            run_id: string;
        };
        /**
         * CredentialId
         * @enum {string}
         */
        CredentialId: "openai" | "anthropic" | "ai33";
        /** CredentialTestRequest */
        CredentialTestRequest: {
            /** Secret */
            secret?: string | null;
        };
        /** CredentialTestResponse */
        CredentialTestResponse: {
            /** Ok */
            ok: boolean;
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /** CredentialUpdateRequest */
        CredentialUpdateRequest: {
            /** Revision */
            revision: string;
            /**
             * Secret
             * Format: password
             */
            secret: string;
        };
        /**
         * ExecutionStatus
         * @enum {string}
         */
        ExecutionStatus: "queued" | "running" | "cancelling" | "cancelled" | "failed" | "interrupted" | "completed";
        /** FileEntryResponse */
        FileEntryResponse: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "directory" | "file";
            /** Size Bytes */
            size_bytes?: number | null;
        };
        /** FileListResponse */
        FileListResponse: {
            /** Path */
            path: string;
            /** Parent */
            parent?: string | null;
            /** Entries */
            entries: components["schemas"]["FileEntryResponse"][];
        };
        /** FileRootResponse */
        FileRootResponse: {
            /** Label */
            label: string;
            /** Path */
            path: string;
        };
        /** FileRootsResponse */
        FileRootsResponse: {
            /** Roots */
            roots: components["schemas"]["FileRootResponse"][];
        };
        /** GlossaryDoc */
        GlossaryDoc: {
            /**
             * Schema
             * @default 1
             */
            schema: number;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Terms */
            terms?: components["schemas"]["GlossaryTerm"][];
            /** Address Terms */
            address_terms?: components["schemas"]["AddressTerm"][];
            style?: components["schemas"]["StyleDecision"];
        };
        /** GlossaryResponse */
        GlossaryResponse: {
            /** Revision */
            revision: string;
            document: components["schemas"]["GlossaryDoc"];
            /**
             * Editor Locked
             * @default false
             */
            editor_locked: boolean;
            /** Lock Reason */
            lock_reason?: string | null;
        };
        /** GlossaryTerm */
        GlossaryTerm: {
            /** Zh */
            zh: string;
            /**
             * Pinyin
             * @default
             */
            pinyin: string;
            /**
             * Vi
             * @default
             */
            vi: string;
            /**
             * En
             * @default
             */
            en: string;
            /**
             * Type
             * @default other
             * @enum {string}
             */
            type: "person" | "place" | "org" | "term" | "dish" | "product" | "other";
            /**
             * Keep Source
             * @default false
             */
            keep_source: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** GlossaryUpdateRequest */
        GlossaryUpdateRequest: {
            /** Revision */
            revision: string;
            document: components["schemas"]["GlossaryDoc"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Method
             * @default
             */
            method: string;
            /**
             * Subject Pronoun
             * @default
             */
            subject_pronoun: string;
            /**
             * Cps Warnings
             * @default 0
             */
            cps_warnings: number;
            /**
             * Address Terms
             * @default 0
             */
            address_terms: number;
            /**
             * Segments
             * @default 0
             */
            segments: number;
            /**
             * Terms
             * @default 0
             */
            terms: number;
        };
        /** JobDetail */
        JobDetail: {
            /** Job Id */
            job_id: string;
            /** Title */
            title: string;
            source?: components["schemas"]["SourceRequest"] | null;
            /** Targets */
            targets: string[];
            execution_status: components["schemas"]["ExecutionStatus"];
            quality_status: components["schemas"]["QualityStatus"];
            /** Stage */
            stage?: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Message
             * @default
             */
            message: string;
            /** Error */
            error?: string | null;
            /** Attention Reasons */
            attention_reasons?: string[];
            active_run?: components["schemas"]["RunResponse"] | null;
            /** Lanes */
            lanes?: components["schemas"]["JobLaneSummary"][];
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            request: components["schemas"]["JobRequestSnapshot"];
            /** Stages */
            stages: components["schemas"]["StageState"][];
            health?: components["schemas"]["HealthResponse"] | null;
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactResponse"][];
            /** Allowed Actions */
            allowed_actions: ("cancel" | "retry" | "retranslate" | "render" | "approve" | "unapprove")[];
            /**
             * Glossary Stale
             * @default false
             */
            glossary_stale: boolean;
        };
        /** JobLaneSummary */
        JobLaneSummary: {
            /**
             * Id
             * @enum {string}
             */
            id: "pipeline" | "tts";
            /**
             * Started
             * @default true
             */
            started: boolean;
            /** Execution Status */
            execution_status: components["schemas"]["ExecutionStatus"] | "not_started";
            quality_status: components["schemas"]["QualityStatus"];
            /** Stage */
            stage?: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Message
             * @default
             */
            message: string;
            /** Error */
            error?: string | null;
            /** Attention Reasons */
            attention_reasons?: string[];
            active_run?: components["schemas"]["RunResponse"] | null;
            latest_run?: components["schemas"]["RunResponse"] | null;
            /** Allowed Actions */
            allowed_actions?: "cancel"[];
        };
        /** JobPage */
        JobPage: {
            /** Items */
            items: components["schemas"]["JobSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** JobRequestSnapshot */
        JobRequestSnapshot: {
            source: components["schemas"]["SourceRequest"];
            /** Targets */
            targets: ("vi" | "en")[];
            /** Formats */
            formats: ("srt" | "ass")[];
            /**
             * Bilingual
             * @default false
             */
            bilingual: boolean;
            /** Output Dir */
            output_dir: string;
        };
        /** JobSummary */
        JobSummary: {
            /** Job Id */
            job_id: string;
            /** Title */
            title: string;
            source?: components["schemas"]["SourceRequest"] | null;
            /** Targets */
            targets: string[];
            execution_status: components["schemas"]["ExecutionStatus"];
            quality_status: components["schemas"]["QualityStatus"];
            /** Stage */
            stage?: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Message
             * @default
             */
            message: string;
            /** Error */
            error?: string | null;
            /** Attention Reasons */
            attention_reasons?: string[];
            active_run?: components["schemas"]["RunResponse"] | null;
            /** Lanes */
            lanes?: components["schemas"]["JobLaneSummary"][];
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** MetaResponse */
        MetaResponse: {
            /** Stages */
            stages: components["schemas"]["StageDescriptor"][];
            /** Targets */
            targets: string[];
            /** Formats */
            formats: string[];
            /** Capabilities */
            capabilities: string[];
            /** Readiness */
            readiness: components["schemas"]["ReadinessItem"][];
        };
        /** OverrideChange */
        OverrideChange: {
            /** Segment Id */
            segment_id: number;
            /** Text */
            text: string | null;
        };
        /** OverrideUpdateRequest */
        OverrideUpdateRequest: {
            /** Revision */
            revision: string;
            /** Changes */
            changes: components["schemas"]["OverrideChange"][];
        };
        /**
         * QualityStatus
         * @enum {string}
         */
        QualityStatus: "needs_review" | "degraded" | "approved";
        /** ReadinessItem */
        ReadinessItem: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "warning" | "blocked";
            /** Detail */
            detail?: string | null;
        };
        /** RunResponse */
        RunResponse: {
            /** Run Id */
            run_id: string;
            /** Job Id */
            job_id: string;
            /**
             * Lane
             * @default pipeline
             * @enum {string}
             */
            lane: "pipeline" | "tts";
            /** Kind */
            kind: string;
            /** From Stage */
            from_stage: string;
            status: components["schemas"]["ExecutionStatus"];
            /** Stage */
            stage?: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Message
             * @default
             */
            message: string;
            /** Error */
            error?: string | null;
            /** Queue Position */
            queue_position?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Event Seq
             * @default 0
             */
            event_seq: number;
        };
        /** SettingsCredentialResponse */
        SettingsCredentialResponse: {
            id: components["schemas"]["CredentialId"];
            /** Label */
            label: string;
            /** Configured */
            configured: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "environment" | "credential_store" | "none";
            /** Editable */
            editable: boolean;
            /** Masked Value */
            masked_value?: "********" | null;
            /** Env Name */
            env_name: string;
        };
        /**
         * SettingsProviderId
         * @enum {string}
         */
        SettingsProviderId: "segment" | "translate" | "tts";
        /** SettingsProviderResponse */
        SettingsProviderResponse: {
            id: components["schemas"]["SettingsProviderId"];
            /** Label */
            label: string;
            /** Provider */
            provider: string;
            /** Model */
            model?: string | null;
            /** Base Url */
            base_url?: string | null;
            credential_id?: components["schemas"]["CredentialId"] | null;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Revision */
            revision: string;
            /** Credential Store Available */
            credential_store_available: boolean;
            /** Providers */
            providers: components["schemas"]["SettingsProviderResponse"][];
            /** Credentials */
            credentials: components["schemas"]["SettingsCredentialResponse"][];
        };
        /** SettingsRevisionRequest */
        SettingsRevisionRequest: {
            /** Revision */
            revision: string;
        };
        /** SourceRequest */
        SourceRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "local" | "url";
            /** Value */
            value: string;
        };
        /** SpokenOverrideUpdateRequest */
        SpokenOverrideUpdateRequest: {
            /** Revision */
            revision: string;
            /** Changes */
            changes: components["schemas"]["OverrideChange"][];
        };
        /** StageDescriptor */
        StageDescriptor: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Short Label */
            short_label?: string | null;
            /** Description */
            description?: string | null;
        };
        /** StageState */
        StageState: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
        };
        /** StyleDecision */
        StyleDecision: {
            /**
             * Speech Register
             * @default
             */
            speech_register: string;
            /**
             * Narrator Self Vi
             * @default
             */
            narrator_self_vi: string;
            /**
             * Audience Vi
             * @default
             */
            audience_vi: string;
            /**
             * Subject Third Person Vi
             * @default
             */
            subject_third_person_vi: string;
        };
        /** SubtitleCue */
        SubtitleCue: {
            /** Segment Id */
            segment_id: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Source Text */
            source_text: string;
            /** Model Text */
            model_text: string;
            /** Effective Text */
            effective_text: string;
            /**
             * Overridden
             * @default false
             */
            overridden: boolean;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /**
             * Base Changed
             * @default false
             */
            base_changed: boolean;
            /**
             * Override State
             * @default none
             * @enum {string}
             */
            override_state: "none" | "manual" | "base_changed" | "stale";
            /** Warnings */
            warnings?: components["schemas"]["SubtitleWarningResponse"][];
            /**
             * Reviewed
             * @default false
             */
            reviewed: boolean;
            /** Cps */
            cps?: number | null;
            /** Line Count */
            line_count?: number | null;
        };
        /** SubtitleResponse */
        SubtitleResponse: {
            /** Revision */
            revision: string;
            /**
             * Language
             * @enum {string}
             */
            language: "vi" | "en";
            /** Cues */
            cues: components["schemas"]["SubtitleCue"][];
            /**
             * Editor Locked
             * @default false
             */
            editor_locked: boolean;
            /**
             * Output Stale
             * @default false
             */
            output_stale: boolean;
        };
        /** SubtitleWarningResponse */
        SubtitleWarningResponse: {
            /** Kind */
            kind: string;
            /** Detail */
            detail: string;
            /** Value */
            value: number;
            /** Limit */
            limit: number;
        };
        /** TtsCueResponse */
        TtsCueResponse: {
            /** Segment Id */
            segment_id: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Subtitle Text */
            subtitle_text: string;
            /** Default Spoken Text */
            default_spoken_text: string;
            /** Effective Spoken Text */
            effective_spoken_text: string;
            /**
             * Override State
             * @default none
             * @enum {string}
             */
            override_state: "none" | "manual" | "base_changed" | "stale";
            /** Room Seconds */
            room_seconds: number;
            /** Predicted Duration */
            predicted_duration?: number | null;
            /** Overflow Seconds */
            overflow_seconds?: number | null;
            /**
             * Speed
             * @default 1
             */
            speed: number;
            /**
             * Preview State
             * @default missing
             * @enum {string}
             */
            preview_state: "missing" | "current" | "stale";
            /** Preview Url */
            preview_url?: string | null;
        };
        /** TtsPreviewRequest */
        TtsPreviewRequest: {
            /** Segment Id */
            segment_id: number;
        };
        /** TtsSettingsUpdateRequest */
        TtsSettingsUpdateRequest: {
            /** Revision */
            revision: string;
            /** Voice Id */
            voice_id: string;
        };
        /** TtsVoicePage */
        TtsVoicePage: {
            /** Items */
            items: components["schemas"]["TtsVoiceResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Credits */
            credits?: number | null;
        };
        /** TtsVoiceResponse */
        TtsVoiceResponse: {
            /** Voice Id */
            voice_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Locale */
            locale?: string | null;
            /** Gender */
            gender?: string | null;
            /** Age */
            age?: string | null;
            /** Category */
            category?: string | null;
            /** Tier */
            tier?: string | null;
            /** Preview Url */
            preview_url?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Calibrated
             * @default false
             */
            calibrated: boolean;
        };
        /** TtsWorkspaceResponse */
        TtsWorkspaceResponse: {
            /** Revision */
            revision: string;
            /**
             * Language
             * @default vi
             * @constant
             */
            language: "vi";
            /**
             * Provider
             * @default vbee
             * @constant
             */
            provider: "vbee";
            /**
             * Provider Ready
             * @default false
             */
            provider_ready: boolean;
            /** Voice Id */
            voice_id?: string | null;
            selected_voice?: components["schemas"]["TtsVoiceResponse"] | null;
            calibration?: components["schemas"]["VoiceCalibrationResponse"] | null;
            /**
             * Subtitle Approved
             * @default false
             */
            subtitle_approved: boolean;
            /**
             * Execution Status
             * @default not_started
             * @enum {string}
             */
            execution_status: "not_started" | "queued" | "running" | "cancelling" | "cancelled" | "failed" | "interrupted" | "completed";
            /** @default needs_review */
            quality_status: components["schemas"]["QualityStatus"];
            latest_run?: components["schemas"]["RunResponse"] | null;
            active_run?: components["schemas"]["RunResponse"] | null;
            /** Attention Reasons */
            attention_reasons?: string[];
            /** Allowed Actions */
            allowed_actions?: ("preview" | "calibrate" | "render" | "cancel" | "approve" | "unapprove")[];
            /** Cues */
            cues?: components["schemas"]["TtsCueResponse"][];
            /**
             * Total Cues
             * @default 0
             */
            total_cues: number;
            /**
             * Uncached Cues
             * @default 0
             */
            uncached_cues: number;
            output?: components["schemas"]["ArtifactResponse"] | null;
            /**
             * Output Stale
             * @default false
             */
            output_stale: boolean;
            /**
             * Editor Locked
             * @default false
             */
            editor_locked: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceCalibrationResponse */
        VoiceCalibrationResponse: {
            /**
             * Provider
             * @default vbee
             * @constant
             */
            provider: "vbee";
            /** Voice Id */
            voice_id: string;
            /** Overhead Sec */
            overhead_sec: number;
            /** Sec Per Syllable */
            sec_per_syllable: number;
            /** Sample Count */
            sample_count: number;
            /** Source Job Id */
            source_job_id?: string | null;
            /** Calibrated At */
            calibrated_at?: string | null;
            /** Revision */
            revision: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    put_credential_api_v1_settings_credentials__credential_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: components["schemas"]["CredentialId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_credential_api_v1_settings_credentials__credential_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: components["schemas"]["CredentialId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsRevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_credential_api_v1_settings_credentials__credential_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: components["schemas"]["CredentialId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tts_voices_api_v1_tts_voices_get: {
        parameters: {
            query?: {
                search?: string;
                page?: number;
                page_size?: number;
                ownership?: "all" | "vbee" | "community";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TtsVoicePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_v1_api_v1_jobs_get: {
        parameters: {
            query?: {
                search?: string;
                execution?: string | null;
                quality?: string | null;
                lane?: "pipeline" | "tts" | "any";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_v1_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retranslate_job_api_v1_jobs__job_id__retranslate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_job_api_v1_jobs__job_id__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_job_api_v1_jobs__job_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unapprove_job_api_v1_jobs__job_id__unapprove_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_glossary_api_v1_jobs__job_id__glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_glossary_api_v1_jobs__job_id__glossary_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossaryUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subtitles_api_v1_jobs__job_id__subtitles__lang__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                lang: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubtitleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_subtitle_overrides_api_v1_jobs__job_id__subtitle_overrides__lang__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                lang: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubtitleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tts_workspace_api_v1_jobs__job_id__tts_vi_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TtsWorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_tts_settings_api_v1_jobs__job_id__tts_vi_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TtsSettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TtsWorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_tts_spoken_overrides_api_v1_jobs__job_id__tts_vi_spoken_overrides_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpokenOverrideUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TtsWorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_tts_api_v1_jobs__job_id__tts_vi_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TtsPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calibrate_tts_api_v1_jobs__job_id__tts_vi_calibrate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_tts_api_v1_jobs__job_id__tts_vi_render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_tts_api_v1_jobs__job_id__tts_vi_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TtsWorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unapprove_tts_api_v1_jobs__job_id__tts_vi_unapprove_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TtsWorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_tts_preview_api_v1_jobs__job_id__tts_vi_previews__segment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                segment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    file_roots_endpoint_api_v1_files_roots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileRootsResponse"];
                };
            };
        };
    };
    list_files_api_v1_files_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_media_api_v1_jobs__job_id__media_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_api_v1_jobs__job_id__artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
